site_name: Ethan Furman
site_url: https://ethanfurman.me
use_directory_urls: true
theme:
  name: dracula
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - toc.integrate
    - content.code.annotate
    - content.code.copy

nav:
  - Home: index.md
  - Research:
      - Overview: research/overview.md
      - Magnetic Skyrmions: research/skyrmions.md
      - Thin Film Fabrication and Characterization: research/thin_films.md
      - Magnetic Proximity Effect: research/mpe.md
  - Projects: projects.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: false
