site_name: Ethan Furman Personal Site
site_url: https://ethanfurman.me
use_directory_urls: true
theme:
  name: dracula
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - toc.integrate
    - content.code.annotate
    - content.code.copy

nav:
  - Home: index.md
  - Self-Study: self_study.md
      - GNNs: self-study/GNN.md
  - Research: research.md
      - Magnetic Skyrmions: research/skyrmions.md
      - Thin Film Fabrication and Characterization: research/thin_films.md
      - Magnetic Proximity Effect: research/mpe.md
  - Projects: projects.md
      - Phonon-Based Calculations of Graphene's Heat Capacity: projects/graphene.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: false
