site_name: Ethan Furman Personal Site
site_url: https://ethanfurman.me
use_directory_urls: true
theme:
  name: dracula
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - toc.integrate
    - content.code.annotate
    - content.code.copy

nav:
  - Home: index.md
  - Self-Study:
      - Quantum Mechanics:
          - Overview: self-study/quantum-mechanics/index.md
          - Chapter 1: self-study/quantum-mechanics/chapter1.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
